CREATE TABLE NORDEA_ACCOUNT_STATEMENT(
TRANSACTIONS_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
DATE DATE,
TRANSACTION_TITLE NVARCHAR(64),
AMOUNT INTEGER,
CATEGORY INTEGER
--CONSTRAINT _pk PRIMARY KEY (DATE, )  
);



--BATCH_NUMBER ESIM. 1/2020....


--CREATE TRIGGER LASKU  AFTER INSERT ON TILAUS 
--BEGIN 
--DELETE FROM MYYNTIRESKONTRA WHERE laskutila ='MYÖHÄSSÄ';
--END;

